-- Insertar marcas de coches comunes
INSERT INTO brands (name) VALUES 
('Abarth'),
('Alfa Romeo'),
('Aston Martin'),
('Audi'),
('Bentley'),
('BMW'),
('Bugatti'),
('Cadillac'),
('Chevrolet'),
('Chrysler'),
('Citroën'),
('Cupra'),
('Dacia'),
('Dodge'),
('Ferrari'),
('Fiat'),
('Ford'),
('Honda'),
('Hyundai'),
('Infiniti'),
('Jaguar'),
('Jeep'),
('Kia'),
('Lamborghini'),
('Land Rover'),
('Lexus'),
('Lotus'),
('Maserati'),
('Mazda'),
('McLaren'),
('Mercedes-Benz'),
('MINI'),
('Mitsubishi'),
('Nissan'),
('Opel'),
('Peugeot'),
('Porsche'),
('Renault'),
('Rolls-Royce'),
('SEAT'),
('Škoda'),
('Smart'),
('Subaru'),
('Suzuki'),
('Tesla'),
('Toyota'),
('Volkswagen'),
('Volvo');

-- Asegurarse de que no hay duplicados y los nombres están correctamente formateados
ON CONFLICT (name) DO NOTHING; 